### PR TITLE
control module pipeline fixes & added control module UTs

### LINKED ISSUE #384: Control module thread handling issues
**Describe the bug**
We add control module in a pipeline via the PipeLine interface using `addControlModule` method. 
- We start the control module in its own thread like any other module
- But we do not join it in wait_for_all or stop or term
- This might cause undefined behaviour & must be fixed

**To Reproduce**
1. Create a pipeline
2. add control module
3. wait for all 
4. Repeat 10 times in same process, see the number of threads /behaviour 

**Expected behavior**
We should handle the pipeline end for control module gracefully

### PR DESCRIPTION
**Pull request by mraduldubey**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #384 

**Description**

Fixed bunch of issues in control module 
1. thread not joining issue 
2. cyclic dependency 

Added ability to print status of the control module as a serialized string

Added tests for control module (none existed) 

**Alternative(s) considered**
None

**Type**

Type Choose one: (Bug fix | Feature | Testing )

**Screenshots (if applicable)**

**Checklist**

- [x] I have read the [Contribution Guidelines](https://github.com/Apra-Labs/ApraPipes/wiki/Contribution-Guidelines)
- [x] I have written Unit Tests
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach

### CODE REVIEW

File: base/include/AbsControlModule.h [hunk 1]
```diff
@@ -18,27 +18,35 @@ class AbsControlModule : public Module {
...
-
-
+	virtual void handleHealthCallback(const APHealthObject& healthObj);
+	/**
+	 * @brief Register external function to be triggered on every health callBack that control modules recieves from the modules.
+	 * In SimpleControlModule, this extention is called at the end of handleHealthCallback function.
+	 * @param function with signature void f(const APHealthObject*, unsigned short)
+	 * @return nothing.
+	 */
+	void register_healthCallback_extention(
```
Comment (kushaljain-apra) [inline base/include/AbsControlModule.h:39]: function name should be in camel case

File: base/include/PipeLine.h [hunk 2]
```diff
@@ -48,7 +49,7 @@ class PipeLine {
 	void term();
 	void wait_for_all(bool ignoreStatus = false);
 	void interrup_wait_for_all();
```
Comment (kushaljain-apra) [inline base/include/PipeLine.h:51]: fix typo in function name

File: base/src/AbsControlModule.cpp [hunk 3]
```diff
@@ -84,11 +92,54 @@ boost::shared_ptr<Module> AbsControlModule::getModuleofRole(std::string role)
...
+		moduleWithRole = moduleRoles[role].lock();
 	}
 	catch (std::out_of_range)
 	{
 		LOG_ERROR << "no module with the role <" << role << "> registered with the control module.";
 	}
 	return moduleWithRole;
+}
+
+void AbsControlModule::register_healthCallback_extention(
```
Comment (kushaljain-apra) [inline base/src/AbsControlModule.cpp:104]: function name should be in camel case

File: base/src/PipeLine.cpp [hunk 4]
```diff
@@ -106,6 +106,7 @@ bool PipeLine::init()
 	{
 		myStatus = PL_INITFAILED;
 		return false;
+		return false;
```
Comment (kushaljain-apra) [inline base/src/PipeLine.cpp:109]: extra return can be removed

File: base/src/PipeLine.cpp [hunk 5]
```diff
@@ -215,6 +225,7 @@ void PipeLine::step()
 			i->get()->queueStep();
 		}
 	}
+	// should controlModule step ?
```
Comment (kushaljain-apra) [inline base/src/PipeLine.cpp:228]: I don't think it makes sense for control module to step

Comment (mraduldubey) [reply base/src/PipeLine.cpp:228]: command  processing also happens when a module steps - I am writing a test where control module steps to process a command

**Review by kushaljain-apra — COMMENTED** [review]
Looks good to me

File: base/include/SimpleControlModule.h [hunk 6]
```diff
@@ -15,13 +15,10 @@ class SimpleControlModule : public AbsControlModule
...
-
 	}
-
-	void handleError(const APErrorObject &error);
-    void handleHealthCallback(const APHealthObject &healthObj);
-
-	// ErrorCallbacks
+	std::string printStatus();
+	void handleError(const APErrorObject &error) override;
+    void handleHealthCallback(const APHealthObject &healthObj) override;
```
Comment (yashrajsapra) [inline base/include/SimpleControlModule.h:21]: Need to reformat the file

File: base/src/AbsControlModule.cpp [hunk 7]
```diff
@@ -84,11 +92,54 @@ boost::shared_ptr<Module> AbsControlModule::getModuleofRole(std::string role)
 	boost::shared_ptr<Module> moduleWithRole = nullptr;
 	try
 	{
-		moduleWithRole = moduleRoles[role];
+		moduleWithRole = moduleRoles[role].lock();
```
Comment (yashrajsapra) [inline base/src/AbsControlModule.cpp:95]: Why we need lock here

File: base/src/Module.cpp [hunk 8]
```diff
@@ -1563,6 +1576,14 @@ bool Module::addEoPFrame(frame_container &frames)
     frames.insert(make_pair(me.first, frame));
   }
 
+  if (myNature == CONTROL)
+  {
+      auto frame = frame_sp(new EoPFrame());
+      auto metadata = framemetadata_sp(new FrameMetadata(FrameMetadata::GENERAL));
+      frame->setMetadata((metadata));
+      frames.insert(make_pair("dummy_eop_ctrl_pin", frame));
```
Comment (yashrajsapra) [inline base/src/Module.cpp:1584]: Can we define dummy pin in #define

File: base/src/Module.cpp [hunk 9]
```diff
@@ -1295,6 +1298,16 @@ bool Module::step()
     {
       throw AIPException(CTRL_MODULE_INVALID_STATE, "Unexpected: " + std::to_string(frames.size()) + " frames remain unprocessed in control module.");
     }
+    if (mPlay)
+    {
+        mProfiler->startProcessingLap();
+        ret = stepNonSource(frames);
```
Comment (yashrajsapra) [inline base/src/Module.cpp:1304]: Why we need if(mPlay) block in term call

**Review by yashrajsapra — CHANGES_REQUESTED** [review]

File: base/src/Module.cpp [hunk 10]
```diff
@@ -178,7 +178,10 @@ Module::Module(Kind nature, string name, ModuleProps _props)
   mPropsChangeMetadata.reset(
       new FrameMetadata(FrameMetadata::FrameType::PROPS_CHANGE));
 }
-Module::~Module() {}
+Module::~Module() 
+{
+    LOG_INFO << "Module destructor <" << myId << ">";
```
[the remark this answers is not in the document]
Comment (mraduldubey) [reply base/src/Module.cpp:183]: Well, technically we should reconsider all our traces at some point. LOG_TRACE currently is more or less same as LOG_INFO in aprapipes. Right now, this is helpful to decipher if module exits properly. If this log had existed before, we would have identified the control thread issues earlier itself. In short, for now, lets keep it. In future, we will do a log sanitation drive

File: base/src/AbsControlModule.cpp (hunk 7 above)
Comment (mraduldubey) [reply base/src/AbsControlModule.cpp:95]: .lock() is the mechanism to get a temporary `shared_ptr` from a `weak_ptr`

File: base/src/Module.cpp (hunk 8 above)
Comment (mraduldubey) [reply base/src/Module.cpp:1584]: yes. will do that

File: base/src/Module.cpp (hunk 9 above)
Comment (mraduldubey) [reply base/src/Module.cpp:1304]: not in term
