### PR TITLE
Fixed Mp4Writer frame buffer modify issue

### LINKED ISSUE #302: Mp4Writer frame data update issue.
**Describe the bug**
In the Mp4writer, for h264 strategy we are updating the h264 frame->data() to make video playback compatible on all video players.
As in we change the nalu separators format as per Mp4 format. 
If the source is connected to multiple modules and Mp4Writer then same frame_sp is passed to multiple modules and Mp4Writer , Now as we change the frame_sp->data() in Mp4writer the updated frame_sp->data() is being sent to other modules connected to the same source and hence causing issues, specifically in H264Decoder wherein h264 data needs to be in annex B format.

**To Reproduce**
Create a pipeline :
Connect a single rtsp source module to MultiMediaQueue , Mp4Writer and H264decoder.

**Expected behavior**
In the Above pipeline the same frame_sp being used in Mp4Writer should be able to be decoded in H264Decoder module

**Screenshots**

**Desktop (please complete the following information):**
 - Version [e.g. chrome, safari]
 - Cuda Version [e.g. 22]
 - Architecture [e.g. x86_64, arm64]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

### PR DESCRIPTION
**Pull request by mohammedzakikochargi**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #302 

**Description**
Fixed the frame_sp buffer modify issue. Earlier the input frame_sp->data() (Nalu seperators) used to get updated to support the video playback capability across all the players. To avoid modifying the frame buffer added a new method in libmp4 to take two buffers, i.e. modified nalu seprators buffer and the incremented frame buffer pointer.

**Alternative(s) considered**

Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**

Type Choose one: (Bug fix)

**Screenshots (if applicable)**

**Checklist**

- [x] I have read the [Contribution Guidelines](https://github.com/Apra-Labs/ApraPipes/wiki/Contribution-Guidelines)
- [x] I have written Unit Tests
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach

### CODE REVIEW

File: base/src/Mp4WriterSink.cpp [hunk 1]
```diff
@@ -368,11 +368,11 @@ bool DetailJpeg::write(frame_container& frames)
 	return true;
 }
 
-uint8_t* DetailH264::AppendSizeInNaluSeprator(short naluType, frame_sp inH264ImageFrame, size_t& frameSize)
+void DetailH264::modifyFrameOnNewSPSPPS(short naluType, frame_sp inH264ImageFrame, uint8_t*& spsPpsBuffer, size_t& spsPpsSize, uint8_t*& frameData, size_t& frameSize)
```
Comment (mraduldubey) [inline base/src/Mp4WriterSink.cpp:371]: *& not required. Just pass the pointer

File: base/src/Mp4WriterSink.cpp [hunk 2]
```diff
@@ -382,44 +382,42 @@ uint8_t* DetailH264::AppendSizeInNaluSeprator(short naluType, frame_sp inH264Ima
...
+		frameData = frameData + 4;
+		frameSize -= 4;
 	}
-	//copy I frame data to the buffer
-	memcpy(newBuffer, tempBuffer, frameSize - spsPpsSize - 4);
-	//set the pointer to the starting of frame
-	newBuffer -= spsPpsSize + 4;
-	return newBuffer;
+	spsPpsBuffer = spsPpsBuffer - spsPpsSize;
+	spsPpsSize += 4;
```
Comment (mraduldubey) [inline base/src/Mp4WriterSink.cpp:420]: put a small comment <SPSPPSBUFFER+NALU><IFRAME>

**Review by mraduldubey — CHANGES_REQUESTED** [review]
make minor changes

**Review by mraduldubey — APPROVED** [review]
