### PR TITLE
Sound record Cleanup

### LINKED ISSUE #77: clear the litter generated by Audio Src test
OK one comment which we can do it as an improvement after this merge, **the tests should always clear any litter generated...** e.g.  Audiotest*.wav files generated here will be left in the developers workspace and sometimes the test will be fooled because of the litter. e.g. file writing fails but a past copy of file exists in the same workspace. 

The solution is to add a destructor to the test  ~sound_record_tests() which deletes the files in a tolerant fashion so that if the file does not exit it does not crash and move to the next file.

_Originally posted by @kumaakh in https://github.com/Apra-Labs/ApraPipes/pull/62#r803097720_

### PR DESCRIPTION
**Pull request by Vinayak-YB**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #77 

**Description**

FileCleaner is added which clears the files generated during test cases.

**Type**

Type Choose one: (Bug fix | Feature | Documentation | Testing | Other)

**Checklist**

- [x] I have read the [Contribution Guidelines](https://github.com/Apra-Labs/ApraPipes/wiki/Contribution-Guidelines)
- [x] I have written Unit Tests
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach

### CODE REVIEW

File: base/test/sound_record_tests.cpp [hunk 1]
```diff
@@ -12,11 +13,30 @@
 #include "Module.h"
 #include<iostream>
 #include<fstream>
+#include<vector>
 
 BOOST_AUTO_TEST_SUITE(sound_record_tests)
 
+struct FileCleaner {
```
Comment (kumaakh) [inline base/test/sound_record_tests.cpp:20]: Can't we reuse the last version of this function that was written earlier... it is never a good idea to copy paste code...
I suggest we move this "struct FileCleaner" int to test_utils and reuse everywhere.  
 Once we do this properly it will become an example for other tests. 
On the contrary if we do it wrong then the wrong habit will get copy pasted to all tesst @mraduldubey 

Rest is all good.

**Review by kumaakh — CHANGES_REQUESTED** [review]

**Review by kumaakh — APPROVED** [review]
